import Head from 'next/head'
import Image from 'next/image'
import Farmers from '../components/molecules/Forms/Farmers'

//COMPONENTS
import HeroSection from '../components/organisms/HeroSection'

export default function Form() {
    return (
        <div>
            <Head>
                <title>Foosion</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/foosion-logo.png" />
            </Head>

            <Farmers></Farmers>
        </div>
    )
}
