import Head from 'next/head'
import Image from 'next/image'
import MobileMenu from '../components/molecules/MobileMenu'
import Footer from '../components/organisms/Footer'

//COMPONENTS
import JoinUs from '../components/organisms/JoinUs'

export default function Form() {
    return (
        <div>
            <Head>
                <title>Foosion</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/foosion-logo.png" />
            </Head>

            <JoinUs></JoinUs>

            <Footer></Footer>
        </div>
    )
}
