import Head from 'next/head'
import Image from 'next/image'

//COMPONENTS
import HeroSection from '../components/organisms/HeroSection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Foosion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/foosion-logo.png" />
      </Head>

      <HeroSection></HeroSection>
    </div>
  )
}
